Test with stock afdo for available kernels

diff --git a/.github/actions/action.yml b/.github/actions/action.yml
--- a/.github/actions/action.yml
+++ b/.github/actions/action.yml
@@ -328,6 +328,21 @@ runs:
         KSUN_DIR="$KERNEL_PLATFORM_DIR/KernelSU-Next"
         mkdir -p "$ARTIFACTS_DIR"
         
+        AFDO_PATH_1="$COMMON_KERNEL_DIR/android/gki/aarch64/afdo/kernel.afdo"
+        AFDO_PATH_2="$COMMON_KERNEL_DIR/gki/aarch64/afdo/kernel.afdo"
+        
+        # Check which one exists
+        if [ -f "$AFDO_PATH_1" ]; then
+            AFDO_PROFILE="$AFDO_PATH_1"
+        elif [ -f "$AFDO_PATH_2" ]; then
+            AFDO_PROFILE="$AFDO_PATH_2"
+        else
+            echo "ERROR: AFDO profile not found!"
+            echo "  Tried: $AFDO_PATH_1"
+            echo "  Tried: $AFDO_PATH_2"
+            exit 1
+        fi
+        
         # Save to environment for later steps
         echo "CONFIG_FOLDER=$CONFIG_DIR" >> "$GITHUB_ENV"
         echo "ARTIFACTS_FOLDER=$ARTIFACTS_DIR" >> "$GITHUB_ENV"
@@ -339,6 +354,7 @@ runs:
         echo "SUSFS_FOLDER=$SUSFS_DIR" >> "$GITHUB_ENV"
         echo "KSU_FOLDER=$KSU_DIR" >> "$GITHUB_ENV"
         echo "KSUN_FOLDER=$KSUN_DIR" >> "$GITHUB_ENV"
+        echo "AFDO_PROFILE_PATH=$AFDO_PROFILE" >> "$GITHUB_ENV"
 
     - name: Get Kernel Version Info
       shell: bash
@@ -391,6 +407,7 @@ runs:
         if [ "${{ env.OP_SUSFS }}" = true ]; then
           echo "   SUSFS Branch: gki-$ANDROID_VERSION-$VERSION.$PATCHLEVEL"
         fi
+        
         echo "::endgroup::"
 
     - name: 🏷️ Set Build Identity (Hardcoded)
@@ -1279,6 +1296,12 @@ runs:
         
         export KCFLAGS="${KCFLAGS:-} $MAP $MPMAP $FPMAP -no-canonical-prefixes -fdiagnostics-color=never -Qunused-arguments -Wno-unused-command-line-argument -D__ANDROID_COMMON_KERNEL__"
         export KCPPFLAGS="${KCPPFLAGS:-} $MAP $MPMAP $FPMAP"
+        
+        cat >> "$COMMON_KERNEL_FOLDER/arch/arm64/configs/gki_defconfig" <<EOF
+        CONFIG_AUTOFDO_CLANG=y
+        EOF
+        
+        export CLANG_AUTOFDO_PROFILE="$AFDO_PROFILE_PATH"
         
         export LLVM=1 LLVM_IAS=1
         export ARCH=arm64 SUBARCH=arm64
